[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

# Edge Functions
[build.edge-functions]
  directory = "netlify/edge-functions"

[[edge_functions]]
  path = "/api/*"
  function = "api-proxy"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
